---
driver:
  name: docker
  use_sudo: false

busser:
  ruby_bindir: '/usr/bin'

provisioner:
  name: chef_zero
  chef_client_path: '/usr/bin/chef-client'

platforms:
  - name: arch
    driver_config:
      image: 'logankoester/archlinux-chef'
      platform: arch
      disable_upstart: true
      require_chef_omnibus: false
      provision_command:
        - pacman -Sy
        - pacman -S --noconfirm --needed supervisor git
        - rm /etc/gemrc
      run_command: 'sh -c "/usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes && /usr/sbin/supervisord -c /etc/supervisord.conf -n"'

suites:
  - name: default
    driver_config:
      hostname: default
    run_list:
      - 'recipe[supervisor]'
      - 'recipe[meteor]'
    data_bags_path: 'test/integration/data_bags'
    attributes:
      meteor:
